DELETE FROM chunk_types WHERE org_id IS NOT NULL;
DELETE FROM chunk_types WHERE org_id IS NULL AND slug IN (
  'IDENTITY', 'MEMORY', 'KNOWLEDGE', 'CONVENTION', 'PRINCIPLE',
  'DECISION', 'RESEARCH', 'PLAN', 'SPEC', 'IMPLEMENTATION',
  'CONSTRAINT', 'LESSON'
);
DROP TABLE IF EXISTS chunk_types;
